[preview]
max_preview_size = 2097152

preview_script = "~/.config/joshuto/preview_file.sh"

preview_shown_hook_script = "~/.config/joshuto/on_preview_shown.sh"
preview_removed_hook_script = "~/.config/joshuto/on_preview_removed.sh"

